name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
  push:
    tags:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            version="${{ github.event.inputs.version }}"
          elif [ "${{ github.ref_type }}" = "tag" ]; then
            version="$GITHUB_REF_NAME"
          else
            echo "Unsupported event type" >&2
            exit 1
          fi

          if [ -z "$version" ]; then
            echo "Version could not be determined" >&2
            exit 1
          fi

          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform Docker image (version + latest)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} \
            --tag ghcr.io/${{ github.repository }}:latest \
            --push \
            --file docker/Dockerfile \
            docker
